# Generated by Django 3.2.6 on 2021-08-08 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('deptno', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('dname', models.CharField(max_length=255)),
                ('loc', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('empno', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('ename', models.CharField(max_length=255)),
                ('job', models.CharField(max_length=255)),
                ('mgr', models.PositiveIntegerField(blank=True, null=True)),
                ('hiredate', models.DateField()),
                ('sal', models.DecimalField(decimal_places=2, max_digits=7)),
                ('comm', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('deptno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.dept')),
            ],
        ),
    ]
